---
- name: Install and configure CloudWatch agent
  hosts: bastion-host
  become: yes
  vars:
    cloudwatch_region: us-east-1
    cloudwatch_namespace: Memory-and-Disk
  tasks:
    - name: Install CloudWatch agent dependencies
      yum:
        name: [perl-Switch, perl-DateTime, perl-Sys-Syslog, perl-LWP-Protocol-https, perl-Digest-SHA.x86_64]
        state: present

    - name: Download and install CloudWatch agent
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
        dest: /tmp/amazon-cloudwatch-agent.rpm

    - name: Install CloudWatch agent
      yum:
        name: /tmp/amazon-cloudwatch-agent.rpm
        state: present

    - name: Configure CloudWatch agent
      blockinfile:
        path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        create: yes
        block: |
          {
            "agent": {
              "metrics_collection_interval": 60,
              "run_as_user": "root"
            },
            "metrics": {
              "append_dimensions": {
                "InstanceId": "${aws:InstanceId}"
              },
              "metrics_collected": {
                "mem": {
                  "measurement": [
                    "mem_used_percent"
                  ]
                },
                "disk": {
                  "measurement": [
                    "used_percent"
                  ],
                  "metrics_collection_interval": 60,
                  "resources": [
                    "/"
                  ]
                }
              }
            },
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/var/log/messages",
                      "log_group_name": "your_log_group_name",
                      "log_stream_name": "{instance_id}-messages",
                      "timezone": "UTC"
                    }
                  ]
                }
              }
            }
          }

    - name: Start CloudWatch agent
      service:
        name: amazon-cloudwatch-agent
        state: started
        enabled: yes
